// TODO
export const DUMMY_SS = {
  originalArray: [29, 10, 14, 37, 14],
  maxValue: 37,
  pseudoCode: ["", "", "", ""],
  states: [
    {
      checking: NaN,
      currentMin: NaN,
      sorted: [],
      swapping: [],
      step: NaN,
    },
    {
      checking: NaN,
      currentMin: 0,
      sorted: [],
      swapping: [],
      step: 0,
    },
    {
      checking: 1,
      currentMin: 0,
      sorted: [],
      swapping: [],
      step: 1,
    },
    {
      checking: 1,
      currentMin: 1,
      sorted: [],
      swapping: [],
      step: 2,
    },
    {
      checking: 2,
      currentMin: 1,
      sorted: [],
      swapping: [],
      step: 1,
    },
    {
      checking: 3,
      currentMin: 1,
      sorted: [],
      swapping: [],
      step: 1,
    },
    {
      checking: 4,
      currentMin: 1,
      sorted: [],
      swapping: [],
      step: 1,
    },
    {
      checking: NaN,
      currentMin: 1,
      sorted: [],
      swapping: [0, 1],
      step: 3,
    },
    {
      checking: NaN,
      currentMin: 0,
      sorted: [0],
      swapping: [],
      step: 3,
    },
    {
      checking: 1,
      currentMin: 1,
      sorted: [0],
      swapping: [],
      step: 0,
    },
    {
      checking: 2,
      currentMin: 1,
      sorted: [0],
      swapping: [],
      step: 1,
    },
    {
      checking: 2,
      currentMin: 2,
      sorted: [0],
      swapping: [],
      step: 2,
    },
    {
      checking: 3,
      currentMin: 2,
      sorted: [0],
      swapping: [],
      step: 1,
    },
    {
      checking: 4,
      currentMin: 2,
      sorted: [0],
      swapping: [],
      step: 1,
    },
    {
      checking: NaN,
      currentMin: 2,
      sorted: [0],
      swapping: [1, 2],
      step: 3,
    },
    {
      checking: NaN,
      currentMin: 0,
      sorted: [0, 1],
      swapping: [],
      step: 3,
    },
  ],
};

